### ISSUE TITLE
最新版0.8的。cookie 每天都失效啊？求助

### ISSUE THREAD

**Issue by daimafengzi** [jerrykuku/luci-app-jd-dailybonus#10]
最新版0.8的。cookie 每天都失效啊？求助
每天都是 cookie    没有重新拨号。第二天也失效

**Comment by jerrykuku** [comment]
晚点更新下0.8.1看看 正在编译中

**Comment by cqash** [comment]
用QQ之类的登录是每天都失效，账号密码就不会

**Comment by fdfangzhou** [comment]
我出现了一直失效的情况，重新登录获取新的cookie还是提示失效

**Comment by cqash** [comment]
> 我出现了一直失效的情况，重新登录获取新的cookie还是提示失效，脚本V1.75

用京东账号和密码登录就没问题，不要用微信或者qq登录

**Comment by fdfangzhou** [comment]
> > 我出现了一直失效的情况，重新登录获取新的cookie还是提示失效，脚本V1.75
> 
> 用京东账号和密码登录就没问题，不要用微信或者qq登录

账号密码登录，还有手机短信验证码登录都试过了，还是提示cookie失效
