### ISSUE TITLE
1.01在MASTER无法正常工作

### ISSUE THREAD

**Issue by ksong008** [jerrykuku/luci-app-jd-dailybonus#106]
昨天编译了最新的1.01，在master版本上，无法执行签到，输出日志也是空的

**Comment by hue715** [comment]
1.0.1版本的run函数使用uci:tset是不是有问题，uci指令不包含tset
![IMG_20210124_020514](https://user-images.githubusercontent.com/22958922/105619763-c0bd3a80-5e30-11eb-83c5-a5753adf19b6.jpg)

**Comment by jerrykuku** [comment]
https://github.com/openwrt/luci/blob/fb6e62ecaf2d4aa77d921581584f37fa2a69bc48/modules/luci-base/luasrc/model/uci.lua#L420

http://openwrt.github.io/luci/api/modules/luci.model.uci.html#Cursor.tset

tset 应该是没问题的

**Comment by ksong008** [comment]
ssh下手动执行node命令，能执行签到。

**Comment by hue715** [comment]
> https://github.com/openwrt/luci/blob/fb6e62ecaf2d4aa77d921581584f37fa2a69bc48/modules/luci-base/luasrc/model/uci.lua#L420
> 
> http://openwrt.github.io/luci/api/modules/luci.model.uci.html#Cursor.tset
> 
> tset 应该是没问题的

1、从官方的案例中看到使用uci:tset，需要在申明中使用require
![IMG_20210124_112518](https://user-images.githubusercontent.com/22958922/105621034-3976c380-5e3e-11eb-84a7-4831a0167092.jpg)

2、从以前官方回答中看到，使用空参数的luci.http.formvalue()需要用for循环
![IMG_20210124_121726](https://user-images.githubusercontent.com/22958922/105621045-6aef8f00-5e3e-11eb-9f19-95e103e22c7f.jpg)

**Comment by hue715** [comment]
> https://github.com/openwrt/luci/blob/fb6e62ecaf2d4aa77d921581584f37fa2a69bc48/modules/luci-base/luasrc/model/uci.lua#L420
> 
> http://openwrt.github.io/luci/api/modules/luci.model.uci.html#Cursor.tset
> 
> tset 应该是没问题的

经过测试，我进行了以下修改并提交PR（由于我不了解json和lua原理，仅供参考）
1、我发现data.auto_run,data.auto_update,data.cookie等数据并没有从网页中获取，因此退回了update_service.htm中部分代码
![image](https://user-images.githubusercontent.com/22958922/105626887-077d5580-5e6e-11eb-9940-f3ebf3e0f0a9.png)

2、另外v1.01出现无法保存cookie问题，以及当cookie无空时，单击“保存cookie”没有报错，因此修改了jd-dailybonus.lua
![image](https://user-images.githubusercontent.com/22958922/105627113-a6ef1800-5e6f-11eb-974e-5d525821c973.png)

**Comment by jerrykuku** [comment]
![image](https://user-images.githubusercontent.com/9485680/105627350-6bede400-5e71-11eb-865d-110378cdcf54.png)
这是post的数据包 data.auto_run,data.auto_update,data.cookie 应该都在里面才对。
可以提示一下你是在什么浏览器下抓取的到数据 是不包含以上数据的么？

**Comment by hue715** [comment]
> 是post的数据包 data.auto_run,data.auto_update,data.cookie 应该都在里面才对。
> 可以提示一下你是在什么浏览器下抓取的到数据 是不包含以上数据的么？

我是在win10下的chrome浏览器下使用，使用1.01出现的情况是，一旦单击“保存cookie”，auto_run和auto_update就会变为0，而且cookie无法保存，在/www/jd-dailybounus.htm内容为空。感觉是update_service.htm没能将数据传递给cookie，cookie2，auto_run等变量，因此我测试将其退回上一版，就可以传值了，这应该可以排除浏览器的问题了。

**Comment by jerrykuku** [comment]
你的1.0.1版本是使用什么方式更新的呢？
如果是直接更新插件ipk,有没有尝试过 重启路由器 或者删除 /tmp/luci-modulecache/下所有文件 和/tmp/luci-indexcache 文件来清除lua缓存？

**Comment by hue715** [comment]
> 你的1.0.1版本是使用什么方式更新的呢？
> 如果是直接更新插件ipk,有没有尝试过 重启路由器 或者删除 /tmp/luci-modulecache/下所有文件 和/tmp/luci-indexcache 文件来清除lua缓存？
> controller 在没有清空缓存前 还会保持之前的lua内容，前后端的数据接口对不上 就不会保存数据。

是直接整体编译的，重启路由器，清缓存都试过，没有用

**Comment by ksong008** [comment]
> > 你的1.0.1版本是使用什么方式更新的呢？
> > 如果是直接更新插件ipk,有没有尝试过 重启路由器 或者删除 /tmp/luci-modulecache/下所有文件 和/tmp/luci-indexcache 文件来清除lua缓存？
> > controller 在没有清空缓存前 还会保持之前的lua内容，前后端的数据接口对不上 就不会保存数据。
> 
> 是直接整体编译的（github.com/project-openwrt/openwrt.git master分支），重启路由器，清缓存都试过，没有用
我和你一样

**Comment by jerrykuku** [comment]
> > 你的1.0.1版本是使用什么方式更新的呢？
> > 如果是直接更新插件ipk,有没有尝试过 重启路由器 或者删除 /tmp/luci-modulecache/下所有文件 和/tmp/luci-indexcache 文件来清除lua缓存？
> > controller 在没有清空缓存前 还会保持之前的lua内容，前后端的数据接口对不上 就不会保存数据。
> 
> 是直接整体编译的（github.com/project-openwrt/openwrt.git master分支），重启路由器，清缓存都试过，没有用

没猜错的话你的op和luci都是官方版吧？

**Comment by hue715** [comment]
> 没猜错的话你的op和luci都是官方版吧？

luci和packages也都是基于官方master

**Comment by jerrykuku** [comment]
那就没错了，我来修复下吧。

**Comment by hue715** [comment]
> 那就没错了，我来修复下吧。

非常感谢，我这边可以正常使用了。

**Comment by ksong008** [comment]
1.02解决了，关闭
