### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by Guard-H** [jerrykuku/luci-app-jd-dailybonus#11]
[root@OpenWrt:/tmp]#opkg install node-request_2.88.2-1_mipsel_24kc.ipk
Unknown package 'node-request'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for node-request found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package node-request.

用E大的OpenWrt固件安装不了。新3路由刷的OpenWrt也是，都是这种提示，无解。N1正常安装。

**Comment by jerrykuku** [comment]
先安装node 仔细看说明

**Comment by Guard-H** [comment]
> 先安装node仔细看说明
试了很多，都安装不行

**Comment by jerrykuku** [comment]
opkg install node

**Comment by Guard-H** [comment]
> opkg安装节点


 root@OpenWrt:~# opkg install node
Package node (v12.15.0-1) installed in root is up to date.
没问题的

**Comment by Guard-H** [comment]
> > opkg安装例程
> 
> root @ OpenWrt：〜＃opkg install节点
> 安装在root中的Package节点（v12.15.0-1）是最新的。
> 没问题的

Collected errors:
 * check_data_file_clashes: Package libstdcpp6 wants to install file /usr/lib/libstdc++.so.6
        But that file is already provided by package  * libstdcpp
 * opkg_install_cmd: Cannot install package node.
