### ISSUE TITLE
扫码获取cookie，扫码显示服务异常，请返回重试

### ISSUE THREAD

**Issue by myzzh5** [jerrykuku/luci-app-jd-dailybonus#115]
![Screenshot_2021-01-26-12-06-46-090_com jingdong a](https://user-images.githubusercontent.com/39124372/105799263-13345d80-5fcf-11eb-84ea-60bc7551b6ce.jpg)

**Comment by Promix953** [comment]
什么版本？是否升级到了最新版？

**Comment by myzzh5** [comment]
![Z$HX1{_665M%G(VLFFV6RS6](https://user-images.githubusercontent.com/39124372/105800037-d2d5df00-5fd0-11eb-81b0-a960a3c936b6.png)

**Comment by myzzh5** [comment]
![W5BB49GW28LXF~3(M(@$I92](https://user-images.githubusercontent.com/39124372/105800644-31e82380-5fd2-11eb-8c3b-763bbdace678.png)

**Comment by 907904228** [comment]
同楼主问题，请问是否已经解决

**Comment by Promix953** [comment]
如果能获取到cookie，但是手机端显示服务异常或者请更新app版本之类的，不用管他，毕竟咱改不了狗东的代码

**Comment by wilsonxu123** [comment]
我也是扫码显示服务异常，请问怎么解决的？

**Comment by Promix953** [comment]
> 我也是扫码显示服务异常，请问怎么解决的？

网页这边能不能获取到cookie？

**Comment by wilsonxu123** [comment]
> > 我也是扫码显示服务异常，请问怎么解决的？
> 
> 网页这边能不能获取到cookie？

已经可以了

**Comment by myzzh5** [comment]
重刷软路由固件解决了
