### ISSUE TITLE
Not fully working in LuCI Master

### ISSUE THREAD

**Issue by nicksun98** [jerrykuku/luci-app-jd-dailybonus#120]
基于[LuCI Master](https://github.com/openwrt/luci)源码编译的`luci-app-jd-dailybonus`基本功能运行很好，但在点击“保存cookie，并马上进行签到”后，会弹出签到窗口，但是并没有logs滚动且无法退出。不过好在后台自动完成的签到，也会在logs栏下显示正常的logs。

```
Tested on x86_64, bcm27xx, aarch64_generic
Theme: Bootstrap, Material, OpenWrt, OpenWrt2020
```

并未在您的[luci-app-argon](https://github.com/jerrykuku/luci-theme-argon)下测试。

很抱歉冒昧的给您提issue，无论能否解决都十分感谢您。如果解决很困难或者没计划支持LuCI Master，请直接关闭此issue，给您增添的不便请谅解。

btw: 能否日后考虑以英文作为此项目Base，增加po翻译

**Comment by jerrykuku** [comment]
应该可以好好的兼容luci master了才是，如果签到后没显示log，多半是前端出了点小错误，需要debug一下。之前有po 文件 但是考虑到项目背景 基本上只有国内用户才用得到，所以去掉了po 采用纯中文。

**Comment by nicksun98** [comment]
谢谢您的回复。我对前端一窍不通，所以只能来提个issue，麻烦您了。提前祝您新春快乐

**Comment by Promix953** [comment]
抱歉手头没有luci master的测试环境，建议试下编译安装最新的master版本，有问题的话给出openwrt的系统日志和浏览器开发者工具中的报错信息

**Comment by nicksun98** [comment]
> 抱歉手头没有luci master的测试环境，建议试下编译安装最新的master版本，有问题的话给出openwrt的系统日志和浏览器开发者工具中的报错信息

System logs无任何报错，目前的情况只存在于显示卡页面。一直是基于当日最新的Luci master源码
![15A562B2-26A1-4E23-926B-178667844134](https://user-images.githubusercontent.com/44309749/106372030-84e12280-63a6-11eb-9b6c-f583d757f7ce.jpeg)

**Comment by Promix953** [comment]
我指的是luci-app-jd-dailybonus的最新代码

**Comment by nicksun98** [comment]
> 我指的是luci-app-jd-dailybonus的最新代码

一直是最新的，v1.0.0以来一直在追新

**Comment by Promix953** [comment]
最新的merge已经没有这个log modal了

**Comment by jerrykuku** [comment]
> 最新的merge已经没有这个log modal了

呵。。。。我都不知道，已经取消了？

**Comment by hue715** [comment]
目前官方luci master中的OenWrt主题无法显示完整界面
### 京东签到界面：
![image](https://user-images.githubusercontent.com/22958922/106544906-4c2a8000-6543-11eb-9b6d-20d38375689b.png)
### 主题界面：
![image](https://user-images.githubusercontent.com/22958922/106544974-6f552f80-6543-11eb-8cf7-002e0bf2dc28.png)

**Comment by Promix953** [comment]
貌似是因为html tag没有正确关闭，我晚上排查一下

**Comment by hue715** [comment]
> 貌似是因为html tag没有正确关闭，我晚上排查一下

非常感谢，目前已正常。

**Comment by nicksun98** [comment]
不再弹出页面，会自动转移到log，已修好，谢谢大佬们的付出
