### ISSUE TITLE
点击 ’手动执行签到‘ 无效

### ISSUE THREAD

**Issue by czxinshui** [jerrykuku/luci-app-jd-dailybonus#125]
点击 ’手动执行签到‘ 跳到，日志页面，然后就空白，没然后，也没有执行定时签到

Wed Feb  3 18:09:46 2021 daemon.err uhttpd[3654]: sh: /usr/share/jd-dailybonus/newapp.sh: Permission denied

**Comment by Promix953** [comment]
刷新日志页面是否有显示，系统日志有没有相关日志

**Comment by czxinshui** [comment]
> 刷新日志页面是否有显示，系统日志有没有相关日志

刷新是没有显示的，系统日志就不知道了。已经换回上一个版本了

**Comment by nmgsky** [comment]
node /usr/share/jd-dailybonus/JD_DailyBonus.js，，用这个，应该能看到点错误代码，应该还是node版本的过，我从0.85一直升到1.02都是这个问题，然后把node升级到最新版本，中间还安装过几个低版本，还是不能用，装会0.85也不能用了，装回当初的node还是不能用，最后把理由彻底恢复最初状态，0.85能用了

**Comment by czxinshui** [comment]
> node /usr/share/jd-dailybonus/JD_DailyBonus.js ，，用这个，应该能看到点错误代码，应该还是node版本的过，我从0.85一直升到1.02都是这个问题，然后把node升级到最新版本，中间还没有安装过几个低版本，还是不能用，装会0.85也不能用了，装回当初的node还是不能用，最后把理由彻底恢复最初状态，0.85能用了。也可能和我用的系统内核底有关吧，一直用着这个版本感觉挺稳定，一直就没再折腾，20年6月的版本

Lean 2月1号升级了内核，不知道和这个有没有关系，OpenWrt R21.1.18是没问题的。OpenWrt R21.2.1不能用

**Comment by ziyangdaoren** [comment]
> node /usr/share/jd-dailybonus/JD_DailyBonus.js，，用这个，应该能看到点错误代码，应该还是node版本的过，我从0.85一直升到1.02都是这个问题，然后把node升级到最新版本，中间还安装过几个低版本，还是不能用，装回0.85也不能用了，装回当初的node还是不能用，最后把路由彻底恢复最初状态，0.85能用了。也可能和我用的系统内核底有关吧，一直用着这个版本感觉挺稳定，一直就没再折腾，20年6月的版本

不是去掉requset依赖了么？

root@OpenWrt:/# node /usr/share/jd-dailybonus/JD_DailyBonus.js 
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'request'
Require stack:
- /usr/share/jd-dailybonus/JD_DailyBonus.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /usr/share/jd-dailybonus/JD_DailyBonus.js:2265:23
    at nobyda (/usr/share/jd-dailybonus/JD_DailyBonus.js:2274:5)
    at Object.<anonymous> (/usr/share/jd-dailybonus/JD_DailyBonus.js:103:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/share/jd-dailybonus/JD_DailyBonus.js' ]
}

**Comment by Promix953** [comment]
> > node /usr/share/jd-dailybonus/JD_DailyBonus.js，，用这个，应该能看到点错误代码，应该还是node版本的过，我从0.85一直升到1.02都是这个问题，然后把node升级到最新版本，中间还安装过几个低版本，还是不能用，装回0.85也不能用了，装回当初的node还是不能用，最后把路由彻底恢复最初状态，0.85能用了。也可能和我用的系统内核底有关吧，一直用着这个版本感觉挺稳定，一直就没再折腾，20年6月的版本
> 
> 不是去掉requset依赖了么？
> 
> root@OpenWrt:/# node /usr/share/jd-dailybonus/JD_DailyBonus.js
> internal/modules/cjs/loader.js:968
> throw err;
> ^
> 
> Error: Cannot find module 'request'
> Require stack:
> 
> * /usr/share/jd-dailybonus/JD_DailyBonus.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:841:27)
>   at Module.require (internal/modules/cjs/loader.js:1025:19)
>   at require (internal/modules/cjs/helpers.js:72:18)
>   at /usr/share/jd-dailybonus/JD_DailyBonus.js:2265:23
>   at nobyda (/usr/share/jd-dailybonus/JD_DailyBonus.js:2274:5)
>   at Object. (/usr/share/jd-dailybonus/JD_DailyBonus.js:103:15)
>   at Module._compile (internal/modules/cjs/loader.js:1137:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
>   at Module.load (internal/modules/cjs/loader.js:985:32) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/usr/share/jd-dailybonus/JD_DailyBonus.js' ]
>   }

去掉的是lua-request，node的request依赖是上游NobyDa的脚本的依赖，去不掉

**Comment by czxinshui** [comment]
最新修改可以用了 还是0777的问题

**Comment by czxinshui** [comment]
> > > node /usr/share/jd-dailybonus/JD_DailyBonus.js，，用这个，应该能看到点错误代码，应该还是node版本的过，我从0.85一直升到1.02都是这个问题，然后把node升级到最新版本，中间还安装过几个低版本，还是不能用，装回0.85也不能用了，装回当初的node还是不能用，最后把路由彻底恢复最初状态，0.85能用了。也可能和我用的系统内核底有关吧，一直用着这个版本感觉挺稳定，一直就没再折腾，20年6月的版本
> > 
> > 
> > 不是去掉requset依赖了么？
> > root@OpenWrt:/# node /usr/share/jd-dailybonus/JD_DailyBonus.js
> > internal/modules/cjs/loader.js:968
> > throw err;
> > ^
> > Error: Cannot find module 'request'
> > Require stack:
> > 
> > * /usr/share/jd-dailybonus/JD_DailyBonus.js
> >   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
> >   at Function.Module._load (internal/modules/cjs/loader.js:841:27)
> >   at Module.require (internal/modules/cjs/loader.js:1025:19)
> >   at require (internal/modules/cjs/helpers.js:72:18)
> >   at /usr/share/jd-dailybonus/JD_DailyBonus.js:2265:23
> >   at nobyda (/usr/share/jd-dailybonus/JD_DailyBonus.js:2274:5)
> >   at Object. (/usr/share/jd-dailybonus/JD_DailyBonus.js:103:15)
> >   at Module._compile (internal/modules/cjs/loader.js:1137:30)
> >   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
> >   at Module.load (internal/modules/cjs/loader.js:985:32) {
> >   code: 'MODULE_NOT_FOUND',
> >   requireStack: [ '/usr/share/jd-dailybonus/JD_DailyBonus.js' ]
> >   }
> 
> 去掉的是lua-request，node的request依赖是上游NobyDa的脚本的依赖，去不掉

你的最新修改增加权限后可以使用，国内更新源有问题很慢

**Comment by Promix953** [comment]
> > > > node /usr/share/jd-dailybonus/JD_DailyBonus.js，，用这个，应该能看到点错误代码，应该还是node版本的过，我从0.85一直升到1.02都是这个问题，然后把node升级到最新版本，中间还安装过几个低版本，还是不能用，装回0.85也不能用了，装回当初的node还是不能用，最后把路由彻底恢复最初状态，0.85能用了。也可能和我用的系统内核底有关吧，一直用着这个版本感觉挺稳定，一直就没再折腾，20年6月的版本
> > > 
> > > 
> > > 不是去掉requset依赖了么？
> > > root@OpenWrt:/# node /usr/share/jd-dailybonus/JD_DailyBonus.js
> > > internal/modules/cjs/loader.js:968
> > > throw err;
> > > ^
> > > Error: Cannot find module 'request'
> > > Require stack:
> > > 
> > > * /usr/share/jd-dailybonus/JD_DailyBonus.js
> > >   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
> > >   at Function.Module._load (internal/modules/cjs/loader.js:841:27)
> > >   at Module.require (internal/modules/cjs/loader.js:1025:19)
> > >   at require (internal/modules/cjs/helpers.js:72:18)
> > >   at /usr/share/jd-dailybonus/JD_DailyBonus.js:2265:23
> > >   at nobyda (/usr/share/jd-dailybonus/JD_DailyBonus.js:2274:5)
> > >   at Object. (/usr/share/jd-dailybonus/JD_DailyBonus.js:103:15)
> > >   at Module._compile (internal/modules/cjs/loader.js:1137:30)
> > >   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
> > >   at Module.load (internal/modules/cjs/loader.js:985:32) {
> > >   code: 'MODULE_NOT_FOUND',
> > >   requireStack: [ '/usr/share/jd-dailybonus/JD_DailyBonus.js' ]
> > >   }
> > 
> > 
> > 去掉的是lua-request，node的request依赖是上游NobyDa的脚本的依赖，去不掉
> 
> 你的最新修改增加权限后可以使用，国内更新源有问题很慢

在lean lede编译后newapp.sh是有运行权限的,面对三无issue，我只能上根治方案
我一直用的GitHub源，国内更新源大概是gitee的问题，可以试试CDN源
