### ISSUE TITLE
最新版无法手动更新脚本

### ISSUE THREAD

**Issue by kilo1220** [jerrykuku/luci-app-jd-dailybonus#126]
页面显示版本号是1.9.0，点手动更新脚本，提示无法获取脚本更新。

**Comment by czxinshui** [comment]
> 页面显示版本号是1.9.0，点手动更新脚本，提示无法获取脚本更新。
是不是编译进Lean最新的固件

**Comment by kilo1220** [comment]
> > 页面显示版本号是1.9.0，点手动更新脚本，提示无法获取脚本更新。
> > 是不是编译进Lean最新的固件

https://github.com/coolsnowwolf/openwrt 用的这个版本的固件

**Comment by czxinshui** [comment]
> > > 页面显示版本号是1.9.0，点手动更新脚本，提示无法获取脚本更新。
> > > 是不是编译进Lean最新的固件
> 
> https://github.com/coolsnowwolf/openwrt用的这个版本的固件

2.1号更新内核之后就这样了。期待其中一方更新

**Comment by Promix953** [comment]
系统日志有没有相关信息？

**Comment by hue715** [comment]
> 系统日志有没有相关信息？

你好，能否下次更新JD_DailyBonus.js时，顺带更新/etc/config/jd-dailybonus中的脚本版本号
![image](https://user-images.githubusercontent.com/22958922/106920616-3f29ae80-6746-11eb-922c-3653249be1b5.png)

**Comment by GWONGJYULEI** [comment]
同样是Lean最新固件，可从 1.9.0 更新至 1.92
