### ISSUE TITLE
请求重新添加“仅Cookie失效时推送”功能

### ISSUE THREAD

**Issue by NottMee** [jerrykuku/luci-app-jd-dailybonus#130]
记得以前版本有这个功能，新版好像没有了，
请求重新添加，感觉成功时不必推送，减少打扰，谢谢

**Comment by icandura** [comment]
同求这个功能，之前在老路由上装的是 0.8.9-20201230 这个版本，
里面有个“失效时推送（仅当cookie失效时推送）”的开关，前几天换了新的路由手动装了新版的APK，发现这个选项消失了。

**Comment by rockbenben** [comment]
这个功能确实很实用，希望可以重新添加
