### ISSUE TITLE
功能建议：增加第三第四帐号的添加界面

### ISSUE THREAD

**Issue by xxp2277** [jerrykuku/luci-app-jd-dailybonus#139]
默认两个帐号，如果有第三第四帐号，按脚本说明在var OtherKey按如下格式添加cookie，
`var OtherKey = '[{"cookie":"pt_key=xxxxxx;pt_pin=yyyyyy"},{"cookie":"pt_key=xxxxxx;pt_pin=yyyyyy"}]'`
仍会导致部分项目无法签到，比如：
京东金融-签壹: 失败, 原因: Cookie失效‼️
京东金融-签贰: 失败, 原因: Cookie失效‼️
京东金融-签叁: 失败, 原因: Cookie失效‼️
京东金融-签肆: 失败, 原因: Cookie失效‼️
京东金融-签伍: 失败, 原因: Cookie失效‼️

另外，未测试升级脚本是否会导致第三第四帐号的cookie失效（确定第一第二帐号cookie不会随更新脚本失效）。
故建议增加第三第四……帐号的添加界面。

**Comment by maplesky** [comment]
最新的源码(#141)已经合并了多 Cookie 配置，请自行编译。

**Comment by xxp2277** [comment]
多谢，回头更新看看。
