### ISSUE TITLE
网络离线状态无法使用二维码获取Cookie，请刷新后重试！

### ISSUE THREAD

**Issue by hahach** [jerrykuku/luci-app-jd-dailybonus#143]
今天的版本打开网页app直接报错。
网络离线状态无法使用二维码获取Cookie，请刷新后重试！

查看了openwrt的系统日志只能找到如下相关错误信息，请作者看看是什么情况

Mon Mar 15 18:57:01 2021 daemon.notice procd: /etc/rc.d/S25jd-dailybonus: lua: /usr/share/jd-dailybonus/gen_cookieset.lua:18: bad argument #1 to 'pairs' (table expected, got nil)
Mon Mar 15 18:57:01 2021 daemon.notice procd: /etc/rc.d/S25jd-dailybonus: stack traceback:
Mon Mar 15 18:57:01 2021 daemon.notice procd: /etc/rc.d/S25jd-dailybonus: 	[C]: in function 'pairs'
Mon Mar 15 18:57:01 2021 daemon.notice procd: /etc/rc.d/S25jd-dailybonus: 	/usr/share/jd-dailybonus/gen_cookieset.lua:18: in main chunk
Mon Mar 15 18:57:01 2021 daemon.notice procd: /etc/rc.d/S25jd-dailybonus: 	[C]: ?
Mon Mar 15 18:57:02 2021 daemon.notice procd: /etc/rc.d/S25jd-dailybonus: Command failed: Not found

**Comment by sol1999** [comment]
同样的问题

**Comment by aglent** [comment]
看来大家都是一样的问题

**Comment by jerrykuku** [comment]
你们是怎么想出来的要网络离线来获取二维码这种操作的？是不是离线状态下也能刷京豆？

**Comment by aglent** [comment]
> 
> 
> 你们是怎么想出来的要网络离线来获取二维码这种操作的？是不是离线状态下也能刷京豆？

前几天编译的上个版本正常 今天编译的一点击菜单 就是报错离线什么的

**Comment by gnusir** [comment]
点击菜单就报错，路由本机实际上是在线的。

**Comment by hahach** [comment]
> 你们是怎么想出来的要网络离线来获取二维码这种操作的？是不是离线状态下也能刷京豆？

巨佬，我们不是傻瓜啊，路由显然是在线的，打开web界面直接就说离线不能获取。

**Comment by EnnawYang** [comment]
https://github.com/coolsnowwolf/lede/issues/6538#issuecomment-799868142

**Comment by jerrykuku** [comment]
jquery 的问题今天修补

**Comment by jerrykuku** [comment]
> > 你们是怎么想出来的要网络离线来获取二维码这种操作的？是不是离线状态下也能刷京豆？
> 
> 巨佬，我们不是傻瓜啊，路由显然是在线的，打开web界面直接就说离线不能获取。
> 
> 我再补充一下，把之前配置里保存的cookie手动填进去再手动运行也是报错的

对于昨天的回答，表示抱歉！！
同时今天已经修复了此问题。

**Comment by hahach** [comment]
问题解决了，感谢
