### ISSUE TITLE
最新京东签到双击输入框无二维码弹出，也无图标可以点击！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [jerrykuku/luci-app-jd-dailybonus#151]
![image](https://user-images.githubusercontent.com/45259624/111870545-56ec8780-89c0-11eb-8dec-bb9acaa33c2f.png)

**Comment by hue715** [comment]
在op官方Master分支下，双击输入框无二维码弹出，此外Openwrt主题下出现报错
![image](https://user-images.githubusercontent.com/22958922/111893430-986f4800-8a3d-11eb-9e0c-4dac13310f2e.png)

**Comment by dunkeng** [comment]
我有类似问题
![00001](https://user-images.githubusercontent.com/22165870/111899471-bc478380-8a67-11eb-90a5-29f9e6bcc8b6.png)
![00002](https://user-images.githubusercontent.com/22165870/111899466-b8b3fc80-8a67-11eb-8f67-9bc3834de416.png)
![00003](https://user-images.githubusercontent.com/22165870/111899470-bbaeed00-8a67-11eb-922d-65045a2a4c56.png)

**Comment by alepennyq** [comment]
我也是这个问题

**Comment by HuaiHan** [comment]
我也是

**Comment by leechaohua** [comment]
我也有这个问题

**Comment by gyj1109** [comment]
一样的问题

**Comment by Trebelwin** [comment]
我也遇到这个问题

**Comment by pfxjacky** [comment]
我遇到用谷歌浏览器弹出了二维码，但是说生成二维码失败。不知道是什么情况。

**Comment by Jacky-Bruse** [comment]
问题一样，也是这样的，期待修复

**Comment by uray2020** [comment]
同样的问题，切换主题也一样

**Comment by liangchaofu** [comment]
同样问题

**Comment by cielpy** [comment]
同样的问题

**Comment by cielpy** [comment]
修复了一下，不太熟悉 luci 开发，可能会有考虑不到的兼容问题，改动很简单，改了一下 CSS selector 使其能找到要找的节点

https://github.com/jerrykuku/luci-app-jd-dailybonus/pull/165 里面有编译好的 ipk

**Comment by liangchaofu** [comment]
> 修复了一下，不太熟悉 luci 开发，可能会有考虑不到的兼容问题，改动很简单，改了一下 CSS selector 使其能找到要找的节点
> 
> #165 里面有编译好的 ipk

试了，保app提示升级到最新版本

**Comment by cielpy** [comment]
> > 修复了一下，不太熟悉 luci 开发，可能会有考虑不到的兼容问题，改动很简单，改了一下 CSS selector 使其能找到要找的节点
> > #165 里面有编译好的 ipk
> 
> 试了，但app提示升级到最新版本
> app已升到最新版了

我第一次也提示升级，后面再扫就没提示了
