### ISSUE TITLE
建议增加企业微信应用消息通知或群机器人

### ISSUE THREAD

**Issue by kan3Git** [jerrykuku/luci-app-jd-dailybonus#159]
Server酱要点进去看消息
`2021年03月29日`` 京东签到~

您的订阅已过期，续费即可在此处直接看到内容。
捐赠收益将同时用于支撑Server酱和其他免费服务的运行。感谢您的支持。
<a href='https://sct.ftqq.com/readpush?id=1383&readkey='>去Server酱查看详情</a>`

参考[srcrs](https://github.com/srcrs)的消息推送：
`#企业微信通知，普通微信可接收
def sendWechat(wex):
    #获得access_token
    url = 'https://qyapi.weixin.qq.com/cgi-bin/gettoken'
    token_param = '?corpid=' + wex['id'] + '&corpsecret=' + wex['secret']
    token_data = requests.get(url + token_param)
    token_data.encoding = 'utf-8'
    token_data = token_data.json()
    access_token = token_data['access_token']
    #发送内容
    content = readFile_text('./log.txt')
    #创建要发送的消息
    data = {
        "touser": "@all",
        "msgtype": "text",
        "agentid": wex['agentld'],
        "text": {"content": content}
    }
    send_url = 'https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=' + access_token
    message = requests.post(send_url,json=data)
    message.encoding = 'utf-8'
    res = message.json()
    print('Wechat send : ' + res['errmsg'])`

企业微信官方文档：
[https://work.weixin.qq.com/api/doc/90000/90135/90235](https://work.weixin.qq.com/api/doc/90000/90135/90235)

或者用企业微信群机器人，跟dingding的一样，我现在简单把dingding改成企业微信群机器人了，上面的应用消息不会改
`   dtoken=$(uci_get_by_type global dd_token)
    if [ ! -z $dtoken ]; then
    	DTJ_FILE=/tmp/jd-djson.json
	echo "{\"msgtype\": \"markdown\",\"markdown\": {\"content\":\"${title}\\n${desc}\"}}" > ${DTJ_FILE}
    	wget-ssl -q --output-document=/dev/null --header="Content-Type: application/json" --post-file=/tmp/jd-djson.json "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${dtoken}"
    fi
`
企业微信官方文档：
[https://work.weixin.qq.com/api/doc/90000/90136/91770](https://work.weixin.qq.com/api/doc/90000/90136/91770)

**Comment by Rainy99** [comment]
同求

**Comment by graytoowolf** [comment]
同求
