### ISSUE TITLE
1.0.5-20210316版京东签到双击输入框无二维码弹出（Openwrt snapshot下）

### ISSUE THREAD

**Issue by hue715** [jerrykuku/luci-app-jd-dailybonus#162]
**描述Bug**
将源码加入Openwrt官方Master，编译后，出现双击输入框无二维码弹出

**复现过程**
1、在Windows和Mac的Chrome浏览器下，使用argon主题，双击输入框无二维码弹出
2、在Windows和Mac的Chrome浏览器下，使用Material主题，双击输入框无二维码弹出
3、在Windows的Edge浏览器下，使用argon主题，双击输入框无二维码弹出
4、尝试清除luci-modulecache，也无效
5、卸载自行编译的京东签到软件，尝试直接安装如下包，依然无法弹出二维码
`https://github.com/maplesky/luci-app-jd-dailybonus/releases/download/v1.0.5-1/luci-app-jd-dailybonus_1.0.5-20210316_all.ipk`

**截图**

- 不论使用argon或Material主题，Chrome中报错都如下：

![image](https://user-images.githubusercontent.com/22958922/113531878-8b855380-95fc-11eb-998b-906575edc973.png)

- 使用[luci-theme-openwrt主题](https://github.com/openwrt/luci/tree/master/themes/luci-theme-openwrt)，界面显示不全：

![image](https://user-images.githubusercontent.com/22958922/113532699-98a34200-95fe-11eb-9dff-0d9326baf2d5.png)

**插件版本:**
 - Openwrt版本：Openwrt SNAPSHOT r18831-0024ceeeeb / LuCI Master git-21.092.39056-d6c696b
 - 主题以及版本：luci-app-argon 	2.2.7
 - 插件版本：1.0.5-20210316

**桌面系统信息:**
 - 系统和版本：windows 10 预览版210312 & MacOS Catalina 10.15.7
 - 浏览器类型以及：Google Chrome 
 - 版本： 89.0.4389.114

**Comment by liangchaofu** [comment]
同样问题，根本不弹扫码页面是为什么。能试的都试过了。
固件版本	OpenWrt 19.07.4 r11208-ce6496d796 / LuCI openwrt-19.07 branch git-20.247.75781-0d0ab01
内核版本	4.14.195

**Comment by asukagyh** [comment]
装上一个版本，获取后复制存好，更新后填入，临时解决

**Comment by zhangsean** [comment]
我编译的openwrt固件，电脑上可以弹出二维码，手机chrome浏览器上双击弹不出二维码。
双击操作不方便，能不能增加一个弹出按钮，专门用来获取二维码。

**Comment by Peenke** [comment]
一样的问题

**Comment by HanXL0824** [comment]
![@I1NLVCD80H`CIHU8@HOMP5](https://user-images.githubusercontent.com/86908565/124479938-5514cb80-ddd9-11eb-93e4-b2ac901d3ba2.png)
为什么双击输入框一直是这样子，弹出一小部分二维码的框
