### ISSUE TITLE
更换uclient-fetch 后钉钉通知失效

### ISSUE THREAD

**Issue by dqylyln** [jerrykuku/luci-app-jd-dailybonus#190]
**描述Bug**

luci-app-jd-dailybonus | 1.0.5-20210316 版本

uclient-fetch 替换wget后，钉钉通知无效。 尝试命令行直接拼接 uclient-fetch 字符串调用无效，去掉-q 观察返回信息为

Downloading 'https://oapi.dingtalk.com/robot/send?access_token=xxxxx'
Connecting to xxx:443
Writing to 'send?access_token=xxxxx'
Cannot open output file: File exists

并且直接在tmp 目录生成了send的文件
![image](https://user-images.githubusercontent.com/878129/127887899-ee69aa52-8ce8-45d1-9898-a8392fe2225a.png)

文件内容为 
root@OpenWrt:/tmp# cat send?access_token\=xxxx
{"errcode":300001,"errmsg":"param error"}
root@OpenWrt:/tmp#

怀疑 uclient-fetch 不支持--header ”Content-Type: application/json“，导致钉钉端无法识别传递的json文件，所以返回参数错误。

**修复过程**
更换成回wget 后问题解决。

修复后代码
   #Dingding
    dtoken=$(uci_get_by_type global dd_token)
    if [ ! -z $dtoken ]; then
        DTJ_FILE=/tmp/jd-djson.json
        echo "{\"msgtype\": \"markdown\",\"markdown\": {\"title\":\"${title}\",\"text\":\"${title} <br/> ${desc}\"}}" > ${DTJ_FILE}
        wget -q --output-document=/dev/null --header="Content-Type: application/json" --post-file=/tmp/jd-djson.json "https://oapi.dingtalk.com/robot/send?access_token=${dtoken}"
    fi

**Comment by hahach** [comment]
这个bug我当天就提了，提交者没当回事好像
