### ISSUE TITLE
脚本有新的了但是更新却显示最新版本

### ISSUE THREAD

**Issue by CharliesTONG** [jerrykuku/luci-app-jd-dailybonus#20]
野比大佬的脚本已经是8月1日版本的，插件里还是7月18日无法更新。

**Comment by ihuaer** [comment]
新版是测试版，路径变了，你可以手动改下 https://github.com/nooodw/JD/blob/master/JD_DailyBonus.js

**Comment by ihuaer** [comment]
新版本是beta版，你可以手动更新，也可以sh里面的143行后面的代码修改强制更新

**Comment by abcaad** [comment]
新签到脚本中版本号所在行多了一列（beta）  所以现在无法获取正确的版本号
修改sh中的80行也可以解决 
remote_ver=$(cat $TEMP_SCRIPT | sed -n '/更新时间/p' | awk '{for (i=1;i<=NF;i++){if ($i ~/v/) {print $i}}}' | sed 's/v//')

**Comment by yufeiyang2008** [comment]
@CharliesTONG 143行改成 if [ $(expr $local_ver \= $remote_ver) -eq 0 ]; then
经测试可以更新，自己捣鼓出来的

**Comment by jackberry** [comment]
> @CharliesTONG 143行改成 if [ $(expr $local_ver/ = $remote_ver) -eq 0 ]; then
> 经测试可以更新，自己捣鼓出来的

sh脚本的143行已改成这个，点更新还是1.37，未检测到新版，还需要做其他修改吗？我看楼下说要更换sh里面的仓库地址

**Comment by yufeiyang2008** [comment]
我只改了143行，在挂梯子网络环境下可以更新，我的是电信宽带，我怀疑是跟访问github的网络环境有关系，还有你改143行的时候不要复制上面代码，直接在源代码上修改，因为上面代码有多余空格
