### ISSUE TITLE
uclient-fetch 好像不支持header

### ISSUE THREAD

**Issue by acooler15** [jerrykuku/luci-app-jd-dailybonus#201]
**描述Bug**
请清晰的描述bug

**复现过程**
请描述如何复现错误r:

**截图**
如果可以尽可能的上传错误的截图

**插件版本:**
 - Openwrt版本
 - 主题以及版本
 - 插件版本

**桌面系统信息:**
 - 系统和版本
 - 浏览器类型以及
 - 版本

**手机系统信息:**
 - 设备类型：【例如 Iphone x】
 - 系统和版本
 - 浏览器类型
 - 版本

**补充说明**
任何补充请在这里叙述.
[project/uclient](https://git.openwrt.org/project/uclient.git)
好像并不支持`--header`

**Comment by hahach** [comment]
我也是醉了，有人pr把钉钉通知这里改回wget好了后，不知道为啥作者又给改回去了.....我说怎么这两天又不通知了，一看代码还是这个坑

**Comment by acooler15** [comment]
> 我也是醉了，有人pr把钉钉通知这里改回wget好了后，不知道为啥作者又给改回去了.....我说怎么这两天又不通知了，一看代码还是这个坑

uclient-fetch默认取代了wget，而uclient-fetch现在是openwrt默认安装的程序，所以直接将命令改为wget并不能用，实际上还是使用的uclient-fetch...

使用curl也是一个不错的选择，curl大小好像有300多k，不过对于能装nodejs的设备应该没啥问题。
还有一个选择，使用nodejs，但是这样可能会有许多代码要修改

**Comment by WYC-2020** [comment]
那就fork回滚一下
