### ISSUE TITLE
扫码无用；签到少数成功，多数失败

### ISSUE THREAD

**Issue by AXBNG** [jerrykuku/luci-app-jd-dailybonus#220]
每天签到都是成功2-5个，失败二十多个

另外扫码获取cookie提示请更新到最新版京东，可明明已经是最新版app了

**Comment by Jason6111** [comment]
换用docker版吧

**Comment by Jason6111** [comment]
![Uploading 255E4808-3682-4F2E-B4C1-78E79A33F0A0.jpeg…]()

**Comment by Jason6111** [comment]
![B5656F0A-7B8D-4142-B679-6AB215E5584B](https://user-images.githubusercontent.com/43496459/147823607-f8b59e7e-ff0d-44ed-8af0-19fff8c711f9.jpeg)

**Comment by zphk** [comment]
> ![B5656F0A-7B8D-4142-B679-6AB215E5584B](https://user-images.githubusercontent.com/43496459/147823607-f8b59e7e-ff0d-44ed-8af0-19fff8c711f9.jpeg)

你这是哪个docker？

**Comment by Jason6111** [comment]
> > ![B5656F0A-7B8D-4142-B679-6AB215E5584B](https://user-images.githubusercontent.com/43496459/147823607-f8b59e7e-ff0d-44ed-8af0-19fff8c711f9.jpeg)
> 
> 你这是哪个docker？

dockerman 青龙加诺兰 这样输入手机号 自己就填进ck了
