### ISSUE TITLE
5.10.89内核编译固件，无法获取Cookie

### ISSUE THREAD

**Issue by qqsir-dev** [jerrykuku/luci-app-jd-dailybonus#221]
**描述Bug**
请清晰的描述bug
仍然无法扫码，即便手动添加Cookie，之前是可以的，但是现在不行了，会显示“脚本终止, 未获取Cookie ‼️”
**复现过程**
请描述如何复现错误r:

**截图**
如果可以尽可能的上传错误的截图

**插件版本:**
 - Openwrt版本
 - 主题以及版本
 - 插件版本

**桌面系统信息:**
 - 系统和版本
 - 浏览器类型以及
 - 版本

**手机系统信息:**
 - 设备类型：【例如 Iphone x】
 - 系统和版本
 - 浏览器类型
 - 版本

**补充说明**
任何补充请在这里叙述.

**Comment by Benjamin23333** [comment]
我也是这样，cookie手动添加的
![image](https://user-images.githubusercontent.com/54323063/148344480-26f611b7-51c1-4c44-ab42-8c404a609795.png)
但是执行签到显示未获取cookie
![image](https://user-images.githubusercontent.com/54323063/148344608-123010bf-18a1-449d-b035-5e8e2a208af0.png)

**Comment by jh0072110** [comment]
+1，插件完全没法用了（当个推送器都不行）

**Comment by Klosw** [comment]
> 我也是这样，cookie手动添加的 但是执行签到显示未获取cookie ![图片](https://user-images.githubusercontent.com/54323063/148344480-26f611b7-51c1-4c44-ab42-8c404a609795.png) ![图片](https://user-images.githubusercontent.com/54323063/148344608-123010bf-18a1-449d-b035-5e8e2a208af0.png)
> 
> 不过我是5.4.162的r2s固件
我也是 R2S 但是一直没弄成功过

**Comment by yuantongkang** [comment]
我也是这样

**Comment by Klosw** [comment]
> 我也是这样

哪个Cookie不能有中文 如果有中文 你要uncode一下
