### ISSUE TITLE
还会维护吗大佬

### ISSUE THREAD

**Issue by AXBNG** [jerrykuku/luci-app-jd-dailybonus#222]
lean源码编译5.10.90内核固件，cookie无法自动添加到脚本，手动复制进去可以执行，然而自动签到也无，系统计划任务中没有看到jd插件的任务。
虽然这个插件现在有点聊胜于无，但还是希望能维护一下，辛苦。

**Comment by AXBNG** [comment]
> 本周维护到可以正常使用
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年1月14日(周五) 上午9:46 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [jerrykuku/luci-app-jd-dailybonus] 还会维护吗大佬 (Issue #222) lean源码编译5.10.90内核固件，cookie无法自动添加到脚本，手动复制进去可以执行，然而自动签到也无，系统计划任务中没有看到jd插件的任务。 虽然这个插件现在有点聊胜于无，但还是希望能维护一下，辛苦。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

万分感谢~

**Comment by xiaren2** [comment]
还是不能用啊

**Comment by AXBNG** [comment]
> 还是不能用啊

这不还没更新呢么，耐心等维护

**Comment by qqsir-dev** [comment]
能用了吗？

**Comment by Benjamin23333** [comment]
> 能用了吗？

再等等吧

**Comment by greatbody** [comment]
开源的东西，应该大家一起来共献，而不是等着大佬。

**Comment by AXBNG** [comment]
> 开源的东西，应该大家一起来共献，而不是等着大佬。

您有事儿吗，gayhub上都有喷子我是小刀拉屁股开了眼了。
人家有才有德是大佬，俺们能力不够的也只能默默支持，尽量做到无才有德，您这样不解决问题只是想站在道德制高点喷两句的岂不是无才无德。

**Comment by AXBNG** [comment]
> 开源的东西，应该大家一起来共献，而不是等着大佬。

您有事儿吗?
有才有德是大佬，俺们无才但尽量做到有德，无才无德是喷子。

**Comment by xiaren2** [comment]
> 开源的东西，应该大家一起来共献，而不是等着大佬。

没事少装比，少舔。

**Comment by ChuJian2** [comment]
> 



> > 开源的东西，应该大家一起来共献，而不是等着大佬。
> 
> 没事少装比，少舔。

 哈哈，没忍住笑了，兄弟够直接。

**Comment by jerrykuku** [comment]
上游脚本已经很久没有更新了。

**Comment by AXBNG** [comment]
> 上游脚本已经很久没有更新了。

其实对这脚本也没太大要求了，京东签到和金融签到还是能签的，就是想能更新一下插件，现在填进去cookie和body不会写进脚本无法执行，定时也不能添加到系统计划任务......

**Comment by snow212-cn** [comment]
现在京东签到和金融签到也挂了，彻底的残废一个

**Comment by Benjamin23333** [comment]
> 上游脚本已经很久没有更新了。

我想问下，可以留一个能用的最终版吗😂，现在这个版本用不了，再往前一个版本是可以用的
当然，这是在您空闲时间的情况下

**Comment by greatbody** [comment]
> > 开源的东西，应该大家一起来共献，而不是等着大佬。
> 
> 没事少装比，少舔。

我就来装逼，我还真不甜，自己修。
