### ISSUE TITLE
无法签到

### ISSUE THREAD

**Issue by swhr0903** [jerrykuku/luci-app-jd-dailybonus#23]
![image](https://user-images.githubusercontent.com/5847541/90331352-356c8d00-dfe6-11ea-9dd3-f33fa7426a07.png)
日志输出个日期就一直卡着不动了

**Comment by jerrykuku** [comment]
node request 安装没？

**Comment by swhr0903** [comment]
装了

**Comment by jerrykuku** [comment]
进入ssh 然后执行  nohup node /usr/share/jd-dailybonus/JD_DailyBonus.js  这个看下 是不是没有安装 coreutils-nohup

**Comment by swhr0903** [comment]
有哦，生成了个nohup文件，我记得没装这个是不能成功安装签到插件的

**Comment by jerrykuku** [comment]
那就执行 node /usr/share/jd-dailybonus/JD_DailyBonus.js

**Comment by swhr0903** [comment]
和在页面上执行差不多，半天没任何信息出来

**Comment by jerrykuku** [comment]
那就检查 node  和node-request 是否安装

**Comment by dl250** [comment]
我的也是一直卡着，都安装了，不知道怎么回事

**Comment by jerrykuku** [comment]
检测方法 就是如上面 因为整个运行机制 就是要在node环境下 使用request 来运行

**Comment by dl250** [comment]
直接编译进入使用没问题，直接安装ipk用不了

**Comment by elsak667** [comment]
我也是一样的问题，今天突然就不能用了，😭，有没有大佬指导一下，上面的办法都用过了

**Comment by solodarker** [comment]
一样的问题，好像安装的都是用不了。必须走编译？

**Comment by ZHDeveloper** [comment]
[基于github actions的京东自动化签到](https://github.com/ZHDeveloper/JD_Sign_Action)
