### ISSUE TITLE
点击京东链接按钮后，openwrt 页面一片空白

### ISSUE THREAD

**Issue by arfaWong** [jerrykuku/luci-app-jd-dailybonus#24]
如图。
![Snipaste_2020-08-18_14-12-57](https://user-images.githubusercontent.com/8801749/90476886-f1e85f00-e15c-11ea-8f3f-987eefb56f1f.png)

**Comment by zxc131415** [comment]
就是这样的啊，他会跳转到京东啊

**Comment by fengsweet** [comment]
后退一下就行了
