### ISSUE TITLE
好多都签到失败了

### ISSUE THREAD

**Issue by cqash** [jerrykuku/luci-app-jd-dailybonus#3]
![image](https://user-images.githubusercontent.com/48862038/86393959-57c57800-bcd0-11ea-9df7-0e4e6d470fea.png)

**Comment by cqash** [comment]
![image](https://user-images.githubusercontent.com/48862038/86394022-7461b000-bcd0-11ea-828d-8fccbe9d1d43.png)

**Comment by cqash** [comment]
原因未知的那些都没签到成功

**Comment by jerrykuku** [comment]
签到脚本最近没更新 等上游更新

**Comment by liby** [comment]
![image](https://user-images.githubusercontent.com/38807139/86486402-c288b900-bd8d-11ea-80c0-6dc140f5ff97.png)

**Comment by liby** [comment]
脚本更新了
![image](https://user-images.githubusercontent.com/38807139/86544529-324b9f00-bf5a-11ea-9287-ca05828ed739.png)
