### ISSUE TITLE
和lean的源码有冲突

### ISSUE THREAD

**Issue by bin20088** [jerrykuku/luci-app-jd-dailybonus#35]
lean源码地址:https://github.com/coolsnowwolf/lede
* check_data_file_clashes: Package node-request wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/lib/node/request/node_modules/verror/lib/verror.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/lib/node/request/node_modules/verror/package.json
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/lib/node/request/package.json
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/lib/node/request/request.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * opkg_install_cmd: Cannot install package node-request.
make[2]: *** [package/install] Error 255
make[1]: *** [/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2

**Comment by jerrykuku** [comment]
尽量自己多找找原因，不是和lean的源码冲突了，我写了祛除了node-request的依赖了，如果你之前编译的时候 git了我的node-request的话，请删除node-request 或者在menuconfig的时候 取消掉node-request的勾选

**Comment by bin20088** [comment]
> 尽量自己多找找原因，不是和lean的源码冲突了，我写了祛除了node-request的依赖了，如果你之前编译的时候 git了我的node-request的话，请删除node-request 或者在menuconfig的时候 取消掉node-request的勾选

明白了，感谢
