### ISSUE TITLE
LEDE openwrt无法安装最新0.8.5

### ISSUE THREAD

**Issue by 523295116** [jerrykuku/luci-app-jd-dailybonus#36]
提示安装不成功。         But that file is already provided by package  * node-request
 * opkg_install_cmd: Cannot install package luci-app-jd-dailybonus.
root@Openwrt:/tmp#

**Comment by ihuaer** [comment]
> 提示安装不成功。 But that file is already provided by package * node-request
> 
> * opkg_install_cmd: Cannot install package luci-app-jd-dailybonus.
>   root@Openwrt:/tmp#

luci-language 取消node-request

**Comment by jerrykuku** [comment]
先卸载掉  node-request
