### ISSUE TITLE
9月26编译出错

### ISSUE THREAD

**Issue by picc745514** [jerrykuku/luci-app-jd-dailybonus#37]
9月26，使用lean的源码，添加luci-app-jd-dailybonus
编译出错，请问怎么处理呢
![QQ截图20200926130757](https://user-images.githubusercontent.com/22932507/94330731-a47fcd00-fff9-11ea-9884-24463f538205.png)

**Comment by mulder125** [comment]
手动取消勾选 node-request (Languages -> Node.js -> node-request)

**Comment by picc745514** [comment]
> 手动取消节点请求（语言-> Node.js->节点请求）

感谢，编译成功
