### ISSUE TITLE
求助：卡在签到信息页面

### ISSUE THREAD

**Issue by transtab** [jerrykuku/luci-app-jd-dailybonus#38]
各位大佬，请问这是为什么。一直卡在这个页面，日志里也只有日期。已按要求安装自行安装Node。用的esir GDQ9.1版本。
![image](https://user-images.githubusercontent.com/23370946/94369884-f3735280-011e-11eb-80f5-2550072c4f30.png)

**Comment by fixcom** [comment]
我也遇到相同的问题，从V0.8.3版本试到0.8.5都是一样的，x86的软路由，脚本安装、配置都没有任何报错，依赖的2个组件也都安装了。

**Comment by jackberry** [comment]
esir的使用没有问题，下载最新插件，然后安装node就可以，自用node插件下载https://r3p.lanzoui.com/i8aDRi5afcf
