### ISSUE TITLE
能否不固定时间   随机签到呢

### ISSUE THREAD

**Issue by Juvenile-lzj** [jerrykuku/luci-app-jd-dailybonus#4]
感觉固定时间  很容易被jd查水表啊

**Comment by jerrykuku** [comment]
多虑了 等上游脚本更新吧

**Comment by kid424** [comment]
Google了一下在cron表达式和执行脚本的命令之间加一句 
/bin/bash -c "sleep $[RANDOM % 180]s";
就可以在设定的时间后面的180秒的范围内随机时间执行。本来据说是crontab会把百分号识别成换行，需要加转义字符\，但实际测试加了转义字符反而识别不出命令。

**Comment by jerrykuku** [comment]
下个版本会考虑

**Comment by Juvenile-lzj** [comment]
大哥牛批

**Comment by jerrykuku** [comment]
新版功能已经添加
