### ISSUE TITLE
直接装最新版本的 不是更新的 会提示node没安装 

### ISSUE THREAD

**Issue by yz41** [jerrykuku/luci-app-jd-dailybonus#40]
![image](https://user-images.githubusercontent.com/49369261/94423133-ba88bb80-01ba-11eb-81ee-97a65c21b0a5.png)

**Comment by ymcoming** [comment]
那就安装撒，node依赖有几十M

**Comment by msfbao** [comment]
> 那就安装撒，node依赖有几十M

Openwrt-LEDE 内核5.4.61 依赖包怎么安装 我空间还够用

**Comment by JackerooOrg** [comment]
安装包在homelede固件的这个位置，上传并安装一下就可以了，xxx（你电脑位置）\HomeLede20201001_内核V5.4.68_测试版\SoftPkgs\packages\node_v12.16.1-2_x86_64.ipk

**Comment by jackberry** [comment]
自用node插件下载https://r3p.lanzoui.com/i8aDRi5afcf
