### ISSUE TITLE
你好最新版本无法运行一直停留在界面

### ISSUE THREAD

**Issue by hipandiary** [jerrykuku/luci-app-jd-dailybonus#45]
![Snipaste_2020-10-09_09-48-34](https://user-images.githubusercontent.com/42132808/95533004-9f1c7c80-0a14-11eb-8921-5f7c45c96b58.png)
ssh后面试过运行提示同样的错误

**Comment by jerrykuku** [comment]
看起来是node 的问题 尝试重新安装node 吧
