### ISSUE TITLE
大神好 Openwrt-LEDE 内核版本5.4.61 一直不能成功签到

### ISSUE THREAD

**Issue by msfbao** [jerrykuku/luci-app-jd-dailybonus#47]
请大神教下 要怎么操作 一直提示
2020-10-14 03:28:34 Wednesday
/usr/share/jd-dailybonus/newapp.sh: line 116: node: not found

这样就不动了

**Comment by liangchaofu** [comment]
安装node

**Comment by honck1** [comment]
9.5之后不是不需要node了吗？
