### ISSUE TITLE
更新脚本，每次需要点2次才能更新

### ISSUE THREAD

**Issue by baiye233** [jerrykuku/luci-app-jd-dailybonus#48]
更新脚本功能，每次第一次点，都是显示“当前已是最新版本”，第二次点才会显示可更新的脚本。导致自动更新脚本一直没更新脚本，需要手动更新。路由器是每天重启的
![1](https://user-images.githubusercontent.com/50758461/96004244-bf619680-0e6d-11eb-8bf3-5c85d7253907.png)
![2](https://user-images.githubusercontent.com/50758461/96004255-c12b5a00-0e6d-11eb-99d6-fcaa6d843e89.png)

**Comment by leogcry22** [comment]
同样的问题，希望能解决

**Comment by coppea** [comment]
是的，我也存在这个问题
