### ISSUE TITLE
V0.8.5问题

### ISSUE THREAD

**Issue by zhangyining215** [jerrykuku/luci-app-jd-dailybonus#53]
浏览器插件报错，提示程序包无效，手动下载压缩包，解压后没有crx文件只是个文件夹

**Comment by zhangyining215** [comment]
谷歌浏览器版本为： 86.0.4240.75（正式版本） （64 位）openwrt版本为：OpenWrt R9.x.x By Lean Mod3.1.54 By dz / LuCI Master (git-19.178.67687-f28a00b) 内核版本为：4.14
--

**Comment by JackerooOrg** [comment]
抓取Cookie还有其他方法，未必就需要使用该插件。

**Comment by jerrykuku** [comment]
> 浏览器插件报错，提示程序包无效，手动下载压缩包，解压后没有crx文件只是个文件夹

压缩包的内容就是个文件夹。自己加载扩展 只能加载文件夹 而不是 crx。自己看下扩展程序页面 的说明
