### ISSUE TITLE
找不到jquery.min.js

### ISSUE THREAD

**Issue by kid424** [jerrykuku/luci-app-jd-dailybonus#7]
按照说明安装并编译了固件，打开后发现最下面两个按钮没反应。开了浏览器调试工具发现是尝试调用/www/luci-static/bootstrap/js/jquery.min.js失败，复制了一个min版jquery过去恢复正常。这个不是很清楚算是这个插件的bug还是主题的bug，总之先提出来也可以帮到同样遇到这个问题的人。

**Comment by jerrykuku** [comment]
新版本已经自带jquery
