### ISSUE TITLE
报错node-request

### ISSUE THREAD

**Issue by wwz09** [jerrykuku/luci-app-jd-dailybonus#75]
But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uri-js/dist/esnext/schemes/urn.d.ts
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uri-js/dist/esnext/schemes/urn.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uri-js/dist/esnext/schemes/urn.js.map
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uri-js/dist/esnext/uri.d.ts
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uri-js/dist/esnext/uri.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uri-js/dist/esnext/uri.js.map
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uri-js/dist/esnext/util.d.ts
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uri-js/dist/esnext/util.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uri-js/dist/esnext/util.js.map
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uri-js/package.json
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uri-js/yarn.lock
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/AUTHORS
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/CHANGELOG.md
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/LICENSE.md
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/README.md
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/bin/uuid
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/index.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/lib/bytesToUuid.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/lib/md5-browser.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/lib/md5.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/lib/rng-browser.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/lib/rng.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/lib/sha1-browser.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/lib/sha1.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/lib/v35.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/package.json
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/v1.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/v3.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/v4.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/uuid/v5.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/verror/.npmignore
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/verror/CHANGES.md
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/verror/CONTRIBUTING.md
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/verror/LICENSE
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/verror/README.md
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/verror/lib/verror.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/node_modules/verror/package.json
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/package.json
	But that file is already provided by package  * luci-app-jd-dailybonus
 * check_data_file_clashes: Package node-request wants to install file /home/wwz09/Openwrt/GDYT/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/usr/lib/node/request/request.js
	But that file is already provided by package  * luci-app-jd-dailybonus
 * opkg_install_cmd: Cannot install package node-request.

**Comment by jerrykuku** [comment]
去软件包 先卸载node-request
