### ISSUE TITLE
如何自定义签到时间。

### ISSUE THREAD

**Issue by simonchan6688** [jerrykuku/luci-app-jd-dailybonus#77]
配置里都是某点05分，我想自行设置为其他时间该如何修改？

**Comment by jerrykuku** [comment]
没有设计自定义分钟

**Comment by LsnmxNB** [comment]
@jerrykuku 后期希望增加时间随机签到

**Comment by jerrykuku** [comment]
原本功能就是在设定时间后180秒内随机签到

**Comment by LsnmxNB** [comment]
> 原本功能就是在设定时间后180秒内随机签到

好的谢谢，https://github.com/jerrykuku/luci-app-jd-dailybonus/issues/77#issuecomment-736960666 有空支持下这脚本，我看别用脚本每天刷到100多豆

**Comment by dafeida** [comment]
> > 原本功能就是在设定时间后180秒内随机签到
> 
> 好的谢谢，https://github.com/lxk0301/jd_scripts 有空支持下这脚本，我看别用脚本每天刷到100多豆

请问这里面的这些脚本怎么运用到这个上面呢？

**Comment by LsnmxNB** [comment]
> > > 原本功能就是在设定时间后180秒内随机签到
> > 
> > 
> > 好的谢谢，https://github.com/lxk0301/jd_scripts 有空支持下这脚本，我看别用脚本每天刷到100多豆
> 
> 请问这里面的这些脚本怎么运用到这个上面呢？

这个得让大佬支持啊，要不你手动添加也行就超级麻烦
https://github.com/lxk0301/jd_scripts/tree/master

**Comment by dafeida** [comment]
> > > > 原本功能就是在设定时间后180秒内随机签到
> > > 
> > > 
> > > 好的谢谢，https://github.com/lxk0301/jd_scripts 有空支持下这脚本，我看别用脚本每天刷到100多豆
> > 
> > 
> > 请问这里面的这些脚本怎么运用到这个上面呢？
> 
> 这个得让大佬支持啊，要不你手动添加也行就超级麻烦
> https://github.com/lxk0301/jd_scripts/tree/master

就是希望能够支持，如果有教程，能自己添加就完美了。

**Comment by LsnmxNB** [comment]
> > > > > 原本功能就是在设定时间后180秒内随机签到
> > > > 
> > > > 
> > > > 好的谢谢，https://github.com/lxk0301/jd_scripts 有空支持下这脚本，我看别用脚本每天刷到100多豆
> > > 
> > > 
> > > 请问这里面的这些脚本怎么运用到这个上面呢？
> > 
> > 
> > 这个得让大佬支持啊，要不你手动添加也行就超级麻烦
> > https://github.com/lxk0301/jd_scripts/tree/master
> 
> 就是希望能够支持，如果有教程，能自己添加就完美了。

发你的连接有官方教程啊，就TM太麻烦了

**Comment by dafeida** [comment]
> > > > > > 原本功能就是在设定时间后180秒内随机签到
> > > > > 
> > > > > 
> > > > > 好的谢谢，https://github.com/lxk0301/jd_scripts 有空支持下这脚本，我看别用脚本每天刷到100多豆
> > > > 
> > > > 
> > > > 请问这里面的这些脚本怎么运用到这个上面呢？
> > > 
> > > 
> > > 这个得让大佬支持啊，要不你手动添加也行就超级麻烦
> > > https://github.com/lxk0301/jd_scripts/tree/master
> > 
> > 
> > 就是希望能够支持，如果有教程，能自己添加就完美了。
> 
> 发你的连接有官方教程啊，就TM太麻烦了

是的，本来想在wrtopen来弄一下，结果看了半天，实在是搞不懂啊。唉！
