### ISSUE TITLE
微信通知看不到每天签到获取了多少京豆

### ISSUE THREAD

**Issue by yufeiyang2008** [jerrykuku/luci-app-jd-dailybonus#78]
2020年12月02日 京东签到~
【签到号一】: 小宇飞扬

【签到概览】: 成功39个, 失败15个

【账号总计】: 576京豆, 57.1钢镚, 0.58红包

【其他总计】: 0.07金贴, 7.64现金

【签到号二】: jd_188036joz

【签到概览】: 成功41个, 失败12个

【账号总计】: 4481京豆, 2.18钢镚, 3红包

【其他总计】: 0.21金贴, 3.15现金

**Comment by jerrykuku** [comment]
已经更新
