### ISSUE TITLE
新版无法签到！~

### ISSUE THREAD

**Issue by brianzc** [jerrykuku/luci-app-jd-dailybonus#8]
#新版本无法签到
![Screenshot of OpenWrt - 客户端 - LuCI](https://user-images.githubusercontent.com/55436609/87212003-f4ca8580-c34e-11ea-8dfa-bd9c0bd7b1af.jpg)
![Screenshot of OpenWrt - 软件包 - LuCI](https://user-images.githubusercontent.com/55436609/87212009-fb58fd00-c34e-11ea-9002-f608a375f761.jpg)

**Comment by brianzc** [comment]
自编译的X86 lede 新版本无法签到  旧版可以

**Comment by jerrykuku** [comment]
可能是权限问题  进ssh 执行下 /usr/share/jd-dailybonus/newapp.sh -r  看看有什么返回结果

**Comment by yonggedebaqi** [comment]
进入 /usr/share/jd-dailybonus/
执行chmod +x JD_DailyBonus.js
就可以了

**Comment by daydayup563** [comment]
@jerrykuku 请问斐讯K3架构arm v7 选择哪个node-request.ipk进行安装啊？麻烦你了。

**Comment by jerrykuku** [comment]
> @jerrykuku 请问斐讯K3架构arm v7 选择哪个node-request.ipk进行安装啊？麻烦你了。

这个可能需要自己编译了

**Comment by mjyhj** [comment]
-ash: /bin/bash: not found

**Comment by mjyhj** [comment]
一样问题，重新编译了固件后就这样了。
装回旧版也是这样签到不了
