### ISSUE TITLE
Server无法推送，且无法更新

### ISSUE THREAD

**Issue by cncqly** [jerrykuku/luci-app-jd-dailybonus#80]
![services_jd-dailybonus](https://user-images.githubusercontent.com/49673592/101281308-316cb100-3809-11eb-9b03-a42a6c98af6e.png)

**Comment by caliban511** [comment]
我这边也是无法推送。而且10月21日的更新在哪里呢？也找不到。

**Comment by jerrykuku** [comment]
版本过老，请更新最新的插件版本
