### ISSUE TITLE
长时间运行，有时候出现卡签到

### ISSUE THREAD

**Issue by WYC-2020** [jerrykuku/luci-app-jd-dailybonus#81]
长时间运行的时候，隔三四天后会出现签到，签到一半就卡住，导致推送也推送失败，只有kill掉这个进程，重新启动，才行，我是两个账号，基本就卡在第二个账号签到，第二个账号签到一半就卡住了

**Comment by jerrykuku** [comment]
什么设备，我的x86 软路由已经跑了半年多没有这个问题
