### ISSUE TITLE
京东商城-京豆: 失败, 需要拼图验证

### ISSUE THREAD

**Issue by zhucaidan** [jerrykuku/luci-app-jd-dailybonus#84]
商城签到出现：京东商城-京豆: 失败, 需要拼图验证

不知道可否有绕过的办法，现在没法领取商城的京豆

**Comment by jerrykuku** [comment]
这个很难说，说实话这不是luci范畴，本插件只是提供了一个 js脚本的运行环境而已。但是目前更新了获取cookie的方法，可以试试看
