### ISSUE TITLE
签到失败，请教

### ISSUE THREAD

**Issue by jameyhhh** [jerrykuku/luci-app-jd-dailybonus#88]
方糖提示：签到cookie失效，是不是我操作有误？ 我是电脑打开谷歌浏览器，安装插件，然后 登录那个领豆网页，然后获取cookie。 可今天就提示失效了，我去检查了下浏览器设置，好像cookie没有被清理啊。  每天都要重新登录获取cookie吗，谢谢大佬

**Comment by czxinshui** [comment]
用手机号码登录可以用15天左右，用账号登录的，经常要再登陆

**Comment by jameyhhh** [comment]
> 用手机号码登录可以用15天左右,用账号登录的,经常要再登陆

感谢感谢，已用手机+验证码登录，
