### ISSUE TITLE
希望加入双时间签到，还有好友互助

### ISSUE THREAD

**Issue by czxinshui** [jerrykuku/luci-app-jd-dailybonus#92]
希望加入双时间签到，还有好友互助

**Comment by yy860926** [comment]
请问，你是怎么安装成功的？我安装编译时make menuconfig #Check LUCI->Applications->luci-app-jd-dailybonus然后就报错了
Makefile:13: /package.mk: No such file or directory
make: *** No rule to make target '/package.mk'.  Stop.
哪个步骤错了么？
