### ISSUE TITLE
扫码的按钮点了没有反应？

### ISSUE THREAD

**Issue by eightsheep67** [jerrykuku/luci-app-jd-dailybonus#94]
换了各种浏览器，点了获取COOKIE，没有任何反应，是什么问题？

**Comment by jerrykuku** [comment]
截图看一下

**Comment by Promix953** [comment]
> 截图看一下

缺少依赖：
lua-cjson
lua-md5
luasec

缺失文件：
/usr/share/jd-dailybonus/requests.lua
/usr/share/jd-dailybonus/jd_cookie.lua

**Comment by Promix953** [comment]
#97

**Comment by jerrykuku** [comment]
楼上已经修复  并且release的ipk已经更新了
