### ISSUE TITLE
1.0.0版本存在的3个问题

### ISSUE THREAD

**Issue by Promix953** [jerrykuku/luci-app-jd-dailybonus#96]
1.缺少依赖：
lua-cjson
lua-md5
luasec

2.缺失文件：
/usr/share/jd-dailybonus/requests.lua
/usr/share/jd-dailybonus/jd_cookie.lua

3.Github源更新脚本使用的jsdeliver cdn存在版本更新不及时的问题
2021.01.20 20:00更新的v1.91，手动检查脚本更新Github和Gitee都还是1.90版本，
建议Github源还是使用原始的GitHub地址：
[https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js](url)

**Comment by Promix953** [comment]
#97

**Comment by jerrykuku** [comment]
已经 merge 谢谢
