### ISSUE TITLE
无法获取cookie

### ISSUE THREAD

**Issue by NyaNyaXin** [jerrykuku/luci-app-jd-dailybonus#98]
点击“获取第一cookie/获取第二cookie”浏览器控制台报 500错误 ，错误如下：
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute call dispatcher target for entry '/admin/services/jd-dailybonus/qrcode'.
The called action terminated with an exception:
/usr/lib/lua/luci/controller/jd-dailybonus.lua:80: module 'jd_cookie' not found:
	no field package.preload['jd_cookie']
	no file './jd_cookie.lua'
	no file '/usr/share/lua/jd_cookie.lua'
	no file '/usr/share/lua/jd_cookie/init.lua'
	no file '/usr/lib/lua/jd_cookie.lua'
	no file '/usr/lib/lua/jd_cookie/init.lua'
	no file '/usr/share/jd-dailybonus/jd_cookie.lua'
	no file './jd_cookie.so'
	no file '/usr/lib/lua/jd_cookie.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

我是少装了什么东西么?

**Comment by jerrykuku** [comment]
进入 ssh
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache/*

或者重启路由
多半是因为lua 缓存没有更新

**Comment by lllAlex2333** [comment]
您好，执行了命令，也重启了路由。仍然是上面的错误提示。

**Comment by smshkwaei** [comment]
进入 ssh
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache/*

1.02执行命令后会弹出扫码，但是京东APP会提示升级APP最新版本，更新了也会一样提示，手上只有1台手机，不知是否个案
